### ISSUE TITLE
Code does not run straight after cloning

### ISSUE THREAD

**Issue by EddyHaigh** [mat-docs/Atlas.FileSessionAPI.Example#8]
I cloned the app and ran it straight away and got issues. It builds fine but doesn't work when simply running. I even have ATLAS 9 installed.
![image](https://github.com/mat-docs/Atlas.FileSessionAPI.Example/assets/23223991/b99a3e9f-e7ad-43a1-b53d-cc4e672263d2)

**Comment by wei-mclarenapplied** [comment]
Hi @EddyHaigh. We have pushed out a newer version of the Nuget package which addresses this. Thanks.

**Comment by EddyHaigh** [comment]
Looks like it has worked, thanks!
